MULTIPLE_QUERIES_SYSTEM_PROMPT = """NDA""" 

MULTIPLE_QUERIES_USER_PROMPT = """NDA"""

HYDE_SYSTEM_PROMPT = """NDA"""

HYDE_USER_PROMPT = """NDA"""

MULTIPLE_DOCS_SYSTEM_PROMPT = """NDA"""

MULTIPLE_DOCS_USER_PROMPT = """NDA"""

STEPBACK_SYSTEM_PROMPT = """NDA"""

STEPBACK_USER_TEMPLATE = """NDA"""
