MULTIPLE_QUERIES_SYSTEM_PROMPT ="""NDA"""
MULTIPLE_QUERIES_USER_PROMPT = """NDA"""


HYDE_SYSTEM_PROMPT = """NDA"""

HYDE_USER_PROMPT = """NDA"""

MULTIPLE_DOCS_SYSTEM_PROMPT = """NDA"""

MULTIPLE_DOCS_USER_PROMPT ="""NDA"""
STEPBACK_SYSTEM_PROMPT = """NDA"""

STEPBACK_USER_TEMPLATE = """NDA"""

EXTRACT_ABBS_FROM_Q_USER_TEMPLATE = """NDA"""

EXTRACT_ABBS_FROM_Q_SYSTEM = """NDA"""


EXTRACT_ABBS_DEF_USER_TEMPLATE = """NDA"""

EXTRACT_ABBS_DEF_SYSTEM ="""NDA"""
CHECK_ABB_TERM_RELEVANCE_USER_TEMPLATE = """NDA"""

CHECK_ABB_TERM_RELEVANCE_SYSTEM = """NDA"""


REPHRASE_W_ABBS_USER_TEMPLATE = """NDA"""

REPHRASE_W_ABBS_SYSTEM = """NDA"""


GRADE_USER_TEMPLATE = """NDA"""

GRADE_SYSTEM = """NDA"""
